services:
  puppeteer:
    container_name: puppeteer
    build: puppeteer/.
    ports:
      - "3000:3000"
    volumes:
      - ./puppeteer/files:/app
  ai-agent:
    container_name: ai-agent
    build: python/.
    ports:
      - "8000:8000"
    volumes:
      - ./python/files:/app
  frontend:
    container_name: frontend
    build: frontend/.
    ports:
      - "5000:5000"
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
