services:
  puppeteer:
    container_name: puppeteer
    build: puppeteer/.
    ports:
      - "3000:3000"
    volumes:
      - ./puppeteer/files:/app
  ai-agent:
    container_name: ai-agent
    build: python/.
    ports:
      - "8000:8000"
    volumes:
      - ./python/files:/app
